{
 "title": "JMeter Exporter",
 "tags": [
  "prometheus",
  "JMeter",
  "JMeter Exporter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "30s,1m,5m,10m" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{job=\"$job\"},instance)"
    }
   },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jmeter_threads{instance=~\"$instance\",state=\"active\"})"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(Ratio_success{instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg((rate(ResponseTime_sum{code=\"200\"}[$interval])/(rate(ResponseTime_count{code=\"200\"}[$interval])>0)))",
     "legendFormat": "Response time"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(avg(rate(Ratio_failure{instance=~\"$instance\"}[$interval]))/avg(rate(Ratio_total{instance=~\"$instance\"}[$interval])))"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Virtual Users vs OK/KO",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "none", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(jmeter_threads{instance=~\"$instance\",state=\"active\"})",
     "legendFormat": "Virtual Users"
    },
    {
     "expr": "sum(rate(Ratio_success{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "Request OK per second"
    },
    {
     "expr": "sum(rate(Ratio_failure{instance=~\"$instance\"}[$interval]))   ",
     "legendFormat": "Request KO per second"
    }
   ]
  },
  {
   "title": "Total Requests vs OK/KO",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "none", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(Ratio_success{instance=~\"$instance\"}[$interval]))/sum(rate(Ratio_total{instance=~\"$instance\"}[$interval])))",
     "legendFormat": "OK"
    },
    {
     "expr": "(sum(rate(Ratio_failure{instance=~\"$instance\"}[$interval]))/sum(rate(Ratio_total{instance=~\"$instance\"}[$interval])))",
     "legendFormat": "KO"
    },
    {
     "expr": "sum(rate(Ratio_total{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "Total Requests per second"
    }
   ]
  },
  {
   "title": "Avg. Response Time vs Virtual Users",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg((rate(ResponseTime_sum{instance=~\"$instance\",code=\"200\"}[$interval])/(rate(ResponseTime_count{instance=~\"$instance\",code=\"200\"}[$interval])>0)))",
     "legendFormat": "Avg Response Time"
    },
    {
     "expr": "sum(jmeter_threads{instance=~\"$instance\",state=\"active\"})",
     "legendFormat": "Virtual Users"
    }
   ]
  },
  {
   "title": "Avg. Response Time vs OK/KO",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg((rate(ResponseTime_sum{instance=~\"$instance\",code=\"200\"}[$interval])/(rate(ResponseTime_count{instance=~\"$instance\",code=\"200\"}[$interval])>0)))",
     "legendFormat": "Avg Response Time"
    },
    {
     "expr": "sum(rate(Ratio_success{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(Ratio_failure{instance=~\"$instance\"}[$interval]))   ",
     "legendFormat": "KO"
    }
   ]
  },
  {
   "title": "OK",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    { "expr": "sum(Ratio_success) by (label) " }
   ]
  },
  {
   "title": "KO",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    { "expr": "sum(Ratio_failure) by (label) " }
   ]
  },
  {
   "title": "OK per Transaction",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(Ratio_success{instance=~\"$instance\"}[$interval])) by (label)",
     "legendFormat": "{{label}} "
    }
   ]
  },
  {
   "title": "KO per Transaction",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(Ratio_failure{instance=~\"$instance\"}[$interval])) by (label)",
     "legendFormat": "{{label}} "
    }
   ]
  },
  { "title": "Response times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Avg. response time",
   "type": "graph",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": " avg (rate(ResponseTime_sum{instance=~\"$instance\",code=~\"1.*|2.*|3.*|4.*|5.*\"}[$interval]) / (rate(ResponseTime_count{instance=~\"$instance\",code=~\"1.*|2.*|3.*|4.*|5.*\"}[$interval])>0)) by (label)",
     "legendFormat": "{{label}} "
    }
   ]
  },
  {
   "title": "Pct response times",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(ResponseTime{instance=~\"$instance\",code=\"200\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  { "title": "Requests per second", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(Ratio_success{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(Ratio_failure{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "KO"
    }
   ]
  },
  {
   "title": "by label",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(Ratio_total{instance=~\"$instance\"}[$interval])) by (label)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "by HTTP code",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(Ratio_total{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "by HTTP code",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(code) (rate(Ratio_failure{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "by label",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (label) (rate(Ratio_failure{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{label}}"
    }
   ]
  },
  { "title": "Test farm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "GC % time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=~\"$instance\",job=~\"$job\"}[1m])",
     "legendFormat": "{{instance}} - {{gc}} "
    }
   ]
  },
  {
   "title": "JVM heap  - free memory by pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 133 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(jvm_memory_pool_bytes_committed {instance=~\"$instance\",job=~\"$job\"}) - (jvm_memory_pool_bytes_used{instance=~\"$instance\",job=~\"$job\"}) ",
     "legendFormat": "{{instance}} - {{pool}}"
    }
   ]
  },
  {
   "title": "JVM heap -  used memory by pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 141 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(jvm_memory_pool_bytes_used{instance=~\"$instance\",job=\"$job\"}) ",
     "legendFormat": "{{instance}} - {{pool}}"
    }
   ]
  },
  {
   "title": "JVM free memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 149 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(jvm_memory_bytes_max {instance=~\"$instance\",job=\"$job\"}) - (jvm_memory_bytes_used{instance=~\"$instance\",job=\"$job\"})",
     "legendFormat": "{{instance}} - {{area}}"
    }
   ]
  }
 ]
}