global:
  scrape_interval:     5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files:

# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']
    relabel_configs:
    - source_labels: [__address__]
      action: replace
      regex: "(.*):.*"
      target_label: instance

  - job_name: 'node'
    static_configs:
    - targets: ['node:9100']
    relabel_configs:
    - source_labels: [__address__]
      action: replace
      regex: "(.*):.*"
      target_label: instance

  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']
    relabel_configs:
    - source_labels: [__address__]
      action: replace
      regex: "(.*):.*"
      target_label: instance
      
  - job_name: 'jmx'
    static_configs:
    - targets: ['sut_konakart:9404']
    - targets: ['renaissance:9404']
    relabel_configs:
    - source_labels: [__address__]
      action: replace
      regex: "(.*):.*"
      target_label: instance

  - job_name: 'jmeter'
    static_configs:
    - targets: ['jmeter:9270']
    relabel_configs:
    - source_labels: [__address__]
      action: replace
      regex: "(.*):.*"
      target_label: instance
